# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(email: "test@test.com", password: "lol123")
User.create(email: "a@b.com", password: "lol123")
Game.create()
Game.create()
Game.create()

CardTemplate.create(color: "black", text: "Why can't I sleep at night?")
CardTemplate.create(color: "black", text: "I got 99 problems but _ ain't one.")
CardTemplate.create(color: "black", text: "What's a girl's best friend?")
CardTemplate.create(color: "black", text: "What's that smell?")
CardTemplate.create(color: "black", text: "This is the way the world ends / This is the way the world ends / Not with a bang but with _.")
CardTemplate.create(color: "black", text: "What is Batman's guilty pleasure?")
CardTemplate.create(color: "black", text: "TSA guidelines now prohibit _ on airplanes.")
CardTemplate.create(color: "black", text: "What ended my last relationship?")
CardTemplate.create(color: "black", text: "MTV's new reality show features eight washed-up celebrities living with _.")
CardTemplate.create(color: "black", text: "I drink to forget _.")
CardTemplate.create(color: "black", text: "I'm sorry, Professor, but I couldn't complete my homework because of _.")
CardTemplate.create(color: "black", text: "Alternative medicine is now embracing the curative powers of _.")
CardTemplate.create(color: "black", text: "What's that sound?")
CardTemplate.create(color: "black", text: "What's the next Happy Meal&reg; toy?")
CardTemplate.create(color: "black", text: "It's a pity that kids these days are all getting involved with _.")
CardTemplate.create(color: "black", text: "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.")
CardTemplate.create(color: "black", text: "_. That's how I want to die.")
CardTemplate.create(color: "black", text: "What does Dick Cheney prefer?")
CardTemplate.create(color: "black", text: "What's the most emo?")
CardTemplate.create(color: "black", text: "Instead of coal, Santa now gives the bad children _.")
CardTemplate.create(color: "black", text: "Next from J.K. Rowling: Harry Potter and the Chamber of _.")
CardTemplate.create(color: "black", text: "A romantic, candlelit dinner would be incomplete without _.")
CardTemplate.create(color: "black", text: "White people like _.")
CardTemplate.create(color: "black", text: "_. Betcha can't have just one!")
CardTemplate.create(color: "black", text: "War!<br><br>What is it good for?")
CardTemplate.create(color: "black", text: "BILLY MAYS HERE FOR _.")
CardTemplate.create(color: "black", text: "_. High five, bro.")
CardTemplate.create(color: "black", text: "During sex, I like to think about _.")
CardTemplate.create(color: "black", text: "What did I bring back from Mexico?")
CardTemplate.create(color: "black", text: "What are my parents hiding from me?")
CardTemplate.create(color: "black", text: "What will always get you laid?")
CardTemplate.create(color: "black", text: "What would grandma find disturbing, yet oddly charming?")
CardTemplate.create(color: "black", text: "What did the U.S. airdrop to the children of Afghanistan?")
CardTemplate.create(color: "black", text: "What helps Obama unwind?")
CardTemplate.create(color: "black", text: "What's there a ton of in heaven?")
CardTemplate.create(color: "black", text: "Major League Baseball has banned _ for giving players an unfair advantage.")
CardTemplate.create(color: "black", text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.")
CardTemplate.create(color: "black", text: "What's the new fad diet?")
CardTemplate.create(color: "black", text: "When I am the President of the United States, I will create the Department of _.")
CardTemplate.create(color: "black", text: "_. It's a trap!")
CardTemplate.create(color: "black", text: "How am I maintaining my relationship status?")
CardTemplate.create(color: "black", text: "What will I bring back in time to convince people that I am a powerful wizard?")
CardTemplate.create(color: "black", text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.")
CardTemplate.create(color: "black", text: "Coming to Broadway this season, _: The Musical.")
CardTemplate.create(color: "black", text: "What's my secret power?")
CardTemplate.create(color: "black", text: "What gives me uncontrollable gas?")
CardTemplate.create(color: "black", text: "But before I kill you, Mr. Bond, I must show you _.")
CardTemplate.create(color: "black", text: "What never fails to liven up the party?")
CardTemplate.create(color: "black", text: "What am I giving up for Lent?")
CardTemplate.create(color: "black", text: "What do old people smell like? ")
CardTemplate.create(color: "black", text: "The class field trip was completely ruined by _.")
CardTemplate.create(color: "black", text: "When Pharaoh remained unmoved, Moses called down a plague of _.")
CardTemplate.create(color: "black", text: "I do not know with which weapons World War III will be fought, but World War IV will be fought with _.")
CardTemplate.create(color: "black", text: "What's Teach for America using to inspire inner city students to succeed?")
CardTemplate.create(color: "black", text: "In Michael Jackson's final moments, he thought about _.")
CardTemplate.create(color: "black", text: "Why do I hurt all over?")
CardTemplate.create(color: "black", text: "Studies show that lab rats navigate mazes 50% faster after being exposed to _.")
CardTemplate.create(color: "black", text: "Why am I sticky?")
CardTemplate.create(color: "black", text: "What's my anti-drug?")
CardTemplate.create(color: "black", text: "And the Academy Award for _ goes to _.")
CardTemplate.create(color: "black", text: "For my next trick, I will pull _ out of _.")
CardTemplate.create(color: "black", text: "_: Good to the last drop.")
CardTemplate.create(color: "black", text: "What did Vin Diesel eat for dinner?")
CardTemplate.create(color: "black", text: "_: kid-tested, mother-approved.")
CardTemplate.create(color: "black", text: "What gets better with age?")
CardTemplate.create(color: "black", text: "I never truly understood _ until I encountered _.")
CardTemplate.create(color: "black", text: "Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _.")
CardTemplate.create(color: "black", text: "Lifetime&reg; presents _, the story of _.")
CardTemplate.create(color: "black", text: "Make a haiku.")
CardTemplate.create(color: "black", text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.")
CardTemplate.create(color: "black", text: "_ is a slippery slope that leads to _.")
CardTemplate.create(color: "black", text: "In a world ravaged by _, our only solace is _.")
CardTemplate.create(color: "black", text: "That's right, I killed _. How, you ask? _.")
CardTemplate.create(color: "black", text: "When I was tripping on acid, _ turned into _.")
CardTemplate.create(color: "black", text: "_ + _ = _.")
CardTemplate.create(color: "black", text: "What's the next superhero/sidekick duo?")
CardTemplate.create(color: "black", text: "Dear Abby,<br><br>I'm having some trouble with _ and would like your advice.")
CardTemplate.create(color: "black", text: "After the earthquake, Sean Penn brought _ to the people of Haiti.")
CardTemplate.create(color: "black", text: "In L.A. County Jail, word is you can trade 200 cigarettes for _.")
CardTemplate.create(color: "black", text: "Maybe she's born with it. Maybe it's _.")
CardTemplate.create(color: "black", text: "Life for American Indians was forever changed when the White Man introduced them to _.")
CardTemplate.create(color: "black", text: "Next on ESPN2, the World Series of _.")
CardTemplate.create(color: "black", text: "Step 1: _. Step 2: _. Step 3: Profit.")
CardTemplate.create(color: "black", text: "Here is the church<br>Here is the steeple<br>Open the doors<br>And there is _.")
CardTemplate.create(color: "black", text: "How did I lose my virginity?")
CardTemplate.create(color: "black", text: "During his childhood, Salvador Dal&iacute; produced hundreds of paintings of _.")
CardTemplate.create(color: "black", text: "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?")
CardTemplate.create(color: "black", text: "What don't you want to find in your Kung Pao chicken?")
CardTemplate.create(color: "black", text: "The Smithsonian Museum of Natural History has just opened an exhibit on _.")
CardTemplate.create(color: "black", text: "Daddy, why is Mommy crying?")

CardTemplate.create(color: "white", text: "Coat hanger abortions.")
CardTemplate.create(color: "white", text: "Man meat.")
CardTemplate.create(color: "white", text: "Autocannibalism.")
CardTemplate.create(color: "white", text: "Vigorous jazz hands.")
CardTemplate.create(color: "white", text: "Flightless birds.")
CardTemplate.create(color: "white", text: "Pictures of boobs.")
CardTemplate.create(color: "white", text: "Doing the right thing.")
CardTemplate.create(color: "white", text: "The violation of our most basic human rights.")
CardTemplate.create(color: "white", text: "Viagra&reg;")
CardTemplate.create(color: "white", text: "Self-loathing.")
CardTemplate.create(color: "white", text: "Spectacular abs.")
CardTemplate.create(color: "white", text: "A balanced breakfast.")
CardTemplate.create(color: "white", text: "Roofies.")
CardTemplate.create(color: "white", text: "Concealing a boner.")
CardTemplate.create(color: "white", text: "Amputees.")
CardTemplate.create(color: "white", text: "The Big Bang.")
CardTemplate.create(color: "white", text: "Former President George W. Bush.")
CardTemplate.create(color: "white", text: "The Rev. Dr. Martin Luther King, Jr.")
CardTemplate.create(color: "white", text: "Smegma.")
CardTemplate.create(color: "white", text: "Being marginalized.")
CardTemplate.create(color: "white", text: "Cuddling.")
CardTemplate.create(color: "white", text: "Laying an egg.")
CardTemplate.create(color: "white", text: "The Pope.")
CardTemplate.create(color: "white", text: "Aaron Burr.")
CardTemplate.create(color: "white", text: "Genital piercings.")
CardTemplate.create(color: "white", text: "Fingering.")
CardTemplate.create(color: "white", text: "A bleached asshole.")
CardTemplate.create(color: "white", text: "Horse meat.")
CardTemplate.create(color: "white", text: "Fear itself.")
CardTemplate.create(color: "white", text: "Science.")
CardTemplate.create(color: "white", text: "Elderly Japanese men.")
CardTemplate.create(color: "white", text: "Stranger danger.")
CardTemplate.create(color: "white", text: "The terrorists.")
CardTemplate.create(color: "white", text: "Praying the gay away.")
CardTemplate.create(color: "white", text: "Same-sex ice dancing.")
CardTemplate.create(color: "white", text: "Ethnic cleansing.")
CardTemplate.create(color: "white", text: "Cheating in the Special Olympics.")
CardTemplate.create(color: "white", text: "German dungeon porn.")
CardTemplate.create(color: "white", text: "Bingeing and purging.")
CardTemplate.create(color: "white", text: "Making a pouty face.")
CardTemplate.create(color: "white", text: "William Shatner.")
CardTemplate.create(color: "white", text: "Heteronormativity.")
CardTemplate.create(color: "white", text: "Nickelback.")
CardTemplate.create(color: "white", text: "Tom Cruise.")
CardTemplate.create(color: "white", text: "The profoundly handicapped.")
CardTemplate.create(color: "white", text: "The placenta.")
CardTemplate.create(color: "white", text: "Chainsaws for hands.")
CardTemplate.create(color: "white", text: "Arnold Schwarzenegger.")
CardTemplate.create(color: "white", text: "An icepick lobotomy.")
CardTemplate.create(color: "white", text: "Goblins.")
CardTemplate.create(color: "white", text: "Object permanence.")
CardTemplate.create(color: "white", text: "Dying.")
CardTemplate.create(color: "white", text: "Foreskin.")
CardTemplate.create(color: "white", text: "A falcon with a cap on its head.")
CardTemplate.create(color: "white", text: "Hormone injections.")
CardTemplate.create(color: "white", text: "Dying of dysentery.")
CardTemplate.create(color: "white", text: "Sexy pillow fights.")
CardTemplate.create(color: "white", text: "The invisible hand.")
CardTemplate.create(color: "white", text: "A really cool hat.")
CardTemplate.create(color: "white", text: "Sean Penn.")
CardTemplate.create(color: "white", text: "Heartwarming orphans.")
CardTemplate.create(color: "white", text: "The clitoris.")
CardTemplate.create(color: "white", text: "The Three-Fifths compromise.")
CardTemplate.create(color: "white", text: "A sad handjob.")
CardTemplate.create(color: "white", text: "Men.")
CardTemplate.create(color: "white", text: "Historically black colleges.")
CardTemplate.create(color: "white", text: "A micropenis.")
CardTemplate.create(color: "white", text: "Raptor attacks.")
CardTemplate.create(color: "white", text: "Agriculture.")
CardTemplate.create(color: "white", text: "Vikings.")
CardTemplate.create(color: "white", text: "Pretending to care.")
CardTemplate.create(color: "white", text: "The Underground Railroad.")
CardTemplate.create(color: "white", text: "My humps.")
CardTemplate.create(color: "white", text: "Being a dick to children.")
CardTemplate.create(color: "white", text: "Geese.")
CardTemplate.create(color: "white", text: "Bling.")
CardTemplate.create(color: "white", text: "Sniffing glue.")
CardTemplate.create(color: "white", text: "The South.")
CardTemplate.create(color: "white", text: "An Oedipus complex.")
CardTemplate.create(color: "white", text: "Eating all of the cookies before the AIDS bake-sale.")
CardTemplate.create(color: "white", text: "Sexting.")
CardTemplate.create(color: "white", text: "YOU MUST CONSTRUCT ADDITIONAL PYLONS.")
CardTemplate.create(color: "white", text: "Mutually-assured destruction.")
CardTemplate.create(color: "white", text: "Sunshine and rainbows.")
CardTemplate.create(color: "white", text: "Count Chocula.")
CardTemplate.create(color: "white", text: "Sharing needles.")
CardTemplate.create(color: "white", text: "Being rich.")
CardTemplate.create(color: "white", text: "Skeletor.")
CardTemplate.create(color: "white", text: "A sausage festival.")
CardTemplate.create(color: "white", text: "Michael Jackson.")
CardTemplate.create(color: "white", text: "Emotions.")
CardTemplate.create(color: "white", text: "Farting and walking away.")
CardTemplate.create(color: "white", text: "The Chinese gymnastics team.")
CardTemplate.create(color: "white", text: "Necrophilia.")
CardTemplate.create(color: "white", text: "Spontaneous human combustion.")
CardTemplate.create(color: "white", text: "Yeast.")
CardTemplate.create(color: "white", text: "Leaving an awkward voicemail.")
CardTemplate.create(color: "white", text: "Dick Cheney.")
CardTemplate.create(color: "white", text: "White people.")
CardTemplate.create(color: "white", text: "Penis envy.")
CardTemplate.create(color: "white", text: "Teaching a robot to love.")
CardTemplate.create(color: "white", text: "Sperm whales.")
CardTemplate.create(color: "white", text: "Scrubbing under the folds.")
CardTemplate.create(color: "white", text: "Panda sex.")
CardTemplate.create(color: "white", text: "Whipping it out.")
CardTemplate.create(color: "white", text: "Catapults.")
CardTemplate.create(color: "white", text: "Masturbation.")
CardTemplate.create(color: "white", text: "Natural selection.")
CardTemplate.create(color: "white", text: "Opposable thumbs.")
CardTemplate.create(color: "white", text: "A sassy black woman.")
CardTemplate.create(color: "white", text: "AIDS.")
CardTemplate.create(color: "white", text: "The KKK.")
CardTemplate.create(color: "white", text: "Figgy pudding.")
CardTemplate.create(color: "white", text: "Seppuku.")
CardTemplate.create(color: "white", text: "Gandhi.")
CardTemplate.create(color: "white", text: "Preteens.")
CardTemplate.create(color: "white", text: "Toni Morrison's vagina.")
CardTemplate.create(color: "white", text: "Five-Dollar Footlongs&trade;")
CardTemplate.create(color: "white", text: "Land mines.")
CardTemplate.create(color: "white", text: "A sea of troubles.")
CardTemplate.create(color: "white", text: "A zesty breakfast burrito.")
CardTemplate.create(color: "white", text: "Christopher Walken.")
CardTemplate.create(color: "white", text: "Friction.")
CardTemplate.create(color: "white", text: "Balls.")
CardTemplate.create(color: "white", text: "Dental dams.")
CardTemplate.create(color: "white", text: "A can of whoop-ass.")
CardTemplate.create(color: "white", text: "A tiny horse.")
CardTemplate.create(color: "white", text: "Waiting 'til marriage.")
CardTemplate.create(color: "white", text: "Authentic Mexican cuisine.")
CardTemplate.create(color: "white", text: "Genghis Khan.")
CardTemplate.create(color: "white", text: "Old-people smell.")
CardTemplate.create(color: "white", text: "Feeding Rosie O'Donnell.")
CardTemplate.create(color: "white", text: "Pixelated bukkake.")
CardTemplate.create(color: "white", text: "Friends with benefits.")
CardTemplate.create(color: "white", text: "The token minority.")
CardTemplate.create(color: "white", text: "The Tempur-Pedic&reg; Swedish Sleep System&trade;")
CardTemplate.create(color: "white", text: "A thermonuclear detonation.")
CardTemplate.create(color: "white", text: "Take-backsies.")
CardTemplate.create(color: "white", text: "The Rapture.")
CardTemplate.create(color: "white", text: "A cooler full of organs.")
CardTemplate.create(color: "white", text: "Sweet, sweet vengeance.")
CardTemplate.create(color: "white", text: "RoboCop.")
CardTemplate.create(color: "white", text: "Keanu Reeves.")
CardTemplate.create(color: "white", text: "Drinking alone.")
CardTemplate.create(color: "white", text: "Giving 110%.")
CardTemplate.create(color: "white", text: "Flesh-eating bacteria.")
CardTemplate.create(color: "white", text: "The American Dream.")
CardTemplate.create(color: "white", text: "Taking off your shirt.")
CardTemplate.create(color: "white", text: "Me time.")
CardTemplate.create(color: "white", text: "A murder most foul.")
CardTemplate.create(color: "white", text: "The inevitable heat death of the universe.")
CardTemplate.create(color: "white", text: "The folly of man.")
CardTemplate.create(color: "white", text: "That thing that electrocutes your abs.")
CardTemplate.create(color: "white", text: "Cards Against Humanity.")
CardTemplate.create(color: "white", text: "Fiery poops.")
CardTemplate.create(color: "white", text: "Poor people.")
CardTemplate.create(color: "white", text: "Edible underpants.")
CardTemplate.create(color: "white", text: "Britney Spears at 55.")
CardTemplate.create(color: "white", text: "All-you-can-eat shrimp for $4.99.")
CardTemplate.create(color: "white", text: "Pooping back and forth. Forever.")
CardTemplate.create(color: "white", text: "Fancy Feast&reg;.")
CardTemplate.create(color: "white", text: "Jewish fraternities.")
CardTemplate.create(color: "white", text: "Being a motherfucking sorcerer.")
CardTemplate.create(color: "white", text: "Pulling out.")
CardTemplate.create(color: "white", text: "Picking up girls at the abortion clinic.")
CardTemplate.create(color: "white", text: "The homosexual agenda.")
CardTemplate.create(color: "white", text: "The Holy Bible.")
CardTemplate.create(color: "white", text: "Passive-agression.")
CardTemplate.create(color: "white", text: "Ronald Reagan.")
CardTemplate.create(color: "white", text: "Vehicular manslaughter.")
CardTemplate.create(color: "white", text: "Nipple blades.")
CardTemplate.create(color: "white", text: "Assless chaps.")
CardTemplate.create(color: "white", text: "Full frontal nudity.")
CardTemplate.create(color: "white", text: "Hulk Hogan.")
CardTemplate.create(color: "white", text: "Daddy issues.")
CardTemplate.create(color: "white", text: "The hardworking Mexican.")
CardTemplate.create(color: "white", text: "Natalie Portman.")
CardTemplate.create(color: "white", text: "Waking up half-naked in a Denny's parking lot.")
CardTemplate.create(color: "white", text: "God.")
CardTemplate.create(color: "white", text: "Sean Connery.")
CardTemplate.create(color: "white", text: "Saxophone solos.")
CardTemplate.create(color: "white", text: "Gloryholes.")
CardTemplate.create(color: "white", text: "The World of Warcraft.")
CardTemplate.create(color: "white", text: "Homeless people.")
CardTemplate.create(color: "white", text: "Scalping.")
CardTemplate.create(color: "white", text: "Darth Vader.")
CardTemplate.create(color: "white", text: "Eating the last known bison.")
CardTemplate.create(color: "white", text: "Guys who don't call.")
CardTemplate.create(color: "white", text: "Hot Pockets&reg;.")
CardTemplate.create(color: "white", text: "A time travel paradox.")
CardTemplate.create(color: "white", text: "The milk man.")
CardTemplate.create(color: "white", text: "Testicular torsion.")
CardTemplate.create(color: "white", text: "Dropping a chandelier on your enemies and riding the rope up.")
CardTemplate.create(color: "white", text: "World peace.")
CardTemplate.create(color: "white", text: "A salty surprise.")
CardTemplate.create(color: "white", text: "Poorly-timed Holocaust jokes.")
CardTemplate.create(color: "white", text: "Smallpox blankets.")
CardTemplate.create(color: "white", text: "Licking things to claim them as your own.")
CardTemplate.create(color: "white", text: "The heart of a child.")
CardTemplate.create(color: "white", text: "Robert Downey, Jr.")
CardTemplate.create(color: "white", text: "Lockjaw.")
CardTemplate.create(color: "white", text: "Eugenics.")
CardTemplate.create(color: "white", text: "A good sniff.")
CardTemplate.create(color: "white", text: "Friendly fire.")
CardTemplate.create(color: "white", text: "The taint; the grundle; the fleshy fun-bridge.")
CardTemplate.create(color: "white", text: "Wearing underwear inside-out to avoid doing laundry.")
CardTemplate.create(color: "white", text: "Hurricane Katrina.")
CardTemplate.create(color: "white", text: "Free samples.")
CardTemplate.create(color: "white", text: "Jerking off into a pool of children's tears.")
CardTemplate.create(color: "white", text: "A foul mouth.")
CardTemplate.create(color: "white", text: "The glass ceiling.")
CardTemplate.create(color: "white", text: "Republicans.")
CardTemplate.create(color: "white", text: "Explosions.")
CardTemplate.create(color: "white", text: "Michelle Obama's arms.")
CardTemplate.create(color: "white", text: "Getting really high.")
CardTemplate.create(color: "white", text: "Attitude.")
CardTemplate.create(color: "white", text: "Sarah Palin.")
CardTemplate.create(color: "white", text: "The &Uuml;bermensch.")
CardTemplate.create(color: "white", text: "Altar boys.")
CardTemplate.create(color: "white", text: "My soul.")
CardTemplate.create(color: "white", text: "My sex life.")
CardTemplate.create(color: "white", text: "Pedophiles.")
CardTemplate.create(color: "white", text: "72 virgins.")
CardTemplate.create(color: "white", text: "Pabst Blue Ribbon.")
CardTemplate.create(color: "white", text: "Domino's&trade; Oreo&trade; Dessert Pizza.")
CardTemplate.create(color: "white", text: "A snapping turtle biting the tip of your penis.")
CardTemplate.create(color: "white", text: "The Blood of Christ.")
CardTemplate.create(color: "white", text: "Half-assed foreplay.")
CardTemplate.create(color: "white", text: "My collection of high-tech sex toys.")
CardTemplate.create(color: "white", text: "A middle-aged man on roller skates.")
CardTemplate.create(color: "white", text: "Bitches.")
CardTemplate.create(color: "white", text: "Bill Nye the Science Guy.")
CardTemplate.create(color: "white", text: "Italians.")
CardTemplate.create(color: "white", text: "A windmill full of corpses.")
CardTemplate.create(color: "white", text: "Adderall&trade;.")
CardTemplate.create(color: "white", text: "Crippling debt.")
CardTemplate.create(color: "white", text: "A stray pube.")
CardTemplate.create(color: "white", text: "Prancing.")
CardTemplate.create(color: "white", text: "Passing a kidney stone.")
CardTemplate.create(color: "white", text: "A brain tumor.")
CardTemplate.create(color: "white", text: "Leprosy.")
CardTemplate.create(color: "white", text: "Puppies!")
CardTemplate.create(color: "white", text: "Bees?")
CardTemplate.create(color: "white", text: "Frolicking.")
CardTemplate.create(color: "white", text: "Repression.")
CardTemplate.create(color: "white", text: "Road head.")
CardTemplate.create(color: "white", text: "A bag of magic beans.")
CardTemplate.create(color: "white", text: "An asymmetric boob job.")
CardTemplate.create(color: "white", text: "Dead parents.")
CardTemplate.create(color: "white", text: "Public ridicule.")
CardTemplate.create(color: "white", text: "A mating display.")
CardTemplate.create(color: "white", text: "A mime having a stroke.")
CardTemplate.create(color: "white", text: "Stephen Hawking talking dirty.")
CardTemplate.create(color: "white", text: "African children.")
CardTemplate.create(color: "white", text: "Mouth herpes.")
CardTemplate.create(color: "white", text: "Overcompensation.")
CardTemplate.create(color: "white", text: "Riding off into the sunset.")
CardTemplate.create(color: "white", text: "Being on fire.")
CardTemplate.create(color: "white", text: "Tangled Slinkys.")
CardTemplate.create(color: "white", text: "Civilian casualties.")
CardTemplate.create(color: "white", text: "Auschwitz.")
CardTemplate.create(color: "white", text: "My genitals.")
CardTemplate.create(color: "white", text: "Not reciprocating oral sex.")
CardTemplate.create(color: "white", text: "Lactation.")
CardTemplate.create(color: "white", text: "Being fabulous.")
CardTemplate.create(color: "white", text: "Shaquille O'Neal's acting career.")
CardTemplate.create(color: "white", text: "My relationship status.")
CardTemplate.create(color: "white", text: "Asians who aren't good at math.")
CardTemplate.create(color: "white", text: "Alcoholism.")
CardTemplate.create(color: "white", text: "Incest.")
CardTemplate.create(color: "white", text: "Grave robbing.")
CardTemplate.create(color: "white", text: "Hope.")
CardTemplate.create(color: "white", text: "8 oz. of sweet Mexican black-tar heroin.")
CardTemplate.create(color: "white", text: "Kids with ass cancer.")
CardTemplate.create(color: "white", text: "Winking at old people.")
CardTemplate.create(color: "white", text: "The Jews.")
CardTemplate.create(color: "white", text: "Justin Bieber.")
CardTemplate.create(color: "white", text: "Doin' it in the butt.")
CardTemplate.create(color: "white", text: "A lifetime of sadness.")
CardTemplate.create(color: "white", text: "The Hamburglar.")
CardTemplate.create(color: "white", text: "Swooping.")
CardTemplate.create(color: "white", text: "Classist undertones.")
CardTemplate.create(color: "white", text: "New Age music.")
CardTemplate.create(color: "white", text: "Not giving a shit about the Third World.")
CardTemplate.create(color: "white", text: "The Kool-Aid Man.")
CardTemplate.create(color: "white", text: "A hot mess.")
CardTemplate.create(color: "white", text: "Tentacle porn.")
CardTemplate.create(color: "white", text: "Lumberjack fantasies.")
CardTemplate.create(color: "white", text: "The gays.")
CardTemplate.create(color: "white", text: "Scientology.")
CardTemplate.create(color: "white", text: "Estrogen.")
CardTemplate.create(color: "white", text: "GoGurt&reg;.")
CardTemplate.create(color: "white", text: "Judge Judy.")
CardTemplate.create(color: "white", text: "Dick fingers.")
CardTemplate.create(color: "white", text: "Racism.")
CardTemplate.create(color: "white", text: "Surprise sex!")
CardTemplate.create(color: "white", text: "Police brutality.")
CardTemplate.create(color: "white", text: "Passable transvestites.")
CardTemplate.create(color: "white", text: "The Virginia Tech Massacre.")
CardTemplate.create(color: "white", text: "When you fart and a little bit comes out.")
CardTemplate.create(color: "white", text: "Oompa-Loompas.")
CardTemplate.create(color: "white", text: "A fetus.")
CardTemplate.create(color: "white", text: "Obesity.")
CardTemplate.create(color: "white", text: "Tasteful sideboob.")
CardTemplate.create(color: "white", text: "Hot people.")
CardTemplate.create(color: "white", text: "BATMAN!")
CardTemplate.create(color: "white", text: "Black people.")
CardTemplate.create(color: "white", text: "A gassy antelope.")
CardTemplate.create(color: "white", text: "Sexual tension.")
CardTemplate.create(color: "white", text: "Third base.")
CardTemplate.create(color: "white", text: "Racially-biased SAT questions.")
CardTemplate.create(color: "white", text: "Porn stars.")
CardTemplate.create(color: "white", text: "A Super Soaker&trade; full of cat pee.")
CardTemplate.create(color: "white", text: "Muhammed (Praise Be Unto Him).")
CardTemplate.create(color: "white", text: "Puberty.")
CardTemplate.create(color: "white", text: "A disappointing birthday party.")
CardTemplate.create(color: "white", text: "An erection that lasts longer than four hours.")
CardTemplate.create(color: "white", text: "White privilege.")
CardTemplate.create(color: "white", text: "Getting so angry that you pop a boner.")
CardTemplate.create(color: "white", text: "Wifely duties.")
CardTemplate.create(color: "white", text: "Two midgets shitting into a bucket.")
CardTemplate.create(color: "white", text: "Queefing.")
CardTemplate.create(color: "white", text: "Wiping her butt.")
CardTemplate.create(color: "white", text: "Golden showers.")
CardTemplate.create(color: "white", text: "Barack Obama.")
CardTemplate.create(color: "white", text: "Nazis.")
CardTemplate.create(color: "white", text: "A robust mongoloid.")
CardTemplate.create(color: "white", text: "An M. Night Shyamalan plot twist.")
CardTemplate.create(color: "white", text: "Getting drunk on mouthwash.")
CardTemplate.create(color: "white", text: "Lunchables&trade;.")
CardTemplate.create(color: "white", text: "Women in yogurt commercials.")
CardTemplate.create(color: "white", text: "John Wilkes Booth.")
CardTemplate.create(color: "white", text: "Powerful thighs.")
CardTemplate.create(color: "white", text: "Mr. Clean, right behind you.")
CardTemplate.create(color: "white", text: "Multiple stab wounds.")
CardTemplate.create(color: "white", text: "Cybernetic enhancements.")
CardTemplate.create(color: "white", text: "Serfdom.")
CardTemplate.create(color: "white", text: "Kanye West.")
CardTemplate.create(color: "white", text: "Women's suffrage.")
CardTemplate.create(color: "white", text: "Children on leashes.")
CardTemplate.create(color: "white", text: "Harry Potter erotica.")
CardTemplate.create(color: "white", text: "The Dance of the Sugar Plum Fairy.")
CardTemplate.create(color: "white", text: "Lance Armstrong's missing testicle.")
CardTemplate.create(color: "white", text: "Parting the Red Sea.")
CardTemplate.create(color: "white", text: "The Amish.")
CardTemplate.create(color: "white", text: "Dead babies.")
CardTemplate.create(color: "white", text: "Child beauty pageants.")
CardTemplate.create(color: "white", text: "AXE Body Spray.")
CardTemplate.create(color: "white", text: "Centaurs.")
CardTemplate.create(color: "white", text: "Copping a feel.")
CardTemplate.create(color: "white", text: "Grandma.")
CardTemplate.create(color: "white", text: "Famine.")
CardTemplate.create(color: "white", text: "The Trail of Tears.")
CardTemplate.create(color: "white", text: "The miracle of childbirth.")
CardTemplate.create(color: "white", text: "Finger painting.")
CardTemplate.create(color: "white", text: "A monkey smoking a cigar.")
CardTemplate.create(color: "white", text: "The Make-A-Wish&reg; Foundation.")
CardTemplate.create(color: "white", text: "Anal beads.")
CardTemplate.create(color: "white", text: "The Force.")
CardTemplate.create(color: "white", text: "Kamikaze pilots.")
CardTemplate.create(color: "white", text: "Dry heaving.")
CardTemplate.create(color: "white", text: "Active listening.")
CardTemplate.create(color: "white", text: "Ghosts.")
CardTemplate.create(color: "white", text: "The Hustle.")
CardTemplate.create(color: "white", text: "Peeing a little bit.")
CardTemplate.create(color: "white", text: "Another goddamn vampire movie.")
CardTemplate.create(color: "white", text: "Shapeshifters.")
CardTemplate.create(color: "white", text: "The Care Bear Stare.")
CardTemplate.create(color: "white", text: "Hot cheese.")
CardTemplate.create(color: "white", text: "A mopey zoo lion.")
CardTemplate.create(color: "white", text: "A defective condom.")
CardTemplate.create(color: "white", text: "Teenage pregnancy.")
CardTemplate.create(color: "white", text: "A Bop It&trade;.")
CardTemplate.create(color: "white", text: "Expecting a burp and vomiting on the floor.")
CardTemplate.create(color: "white", text: "Horrifying laser hair removal accidents.")
CardTemplate.create(color: "white", text: "Boogers.")
CardTemplate.create(color: "white", text: "Unfathomable stupidity.")
CardTemplate.create(color: "white", text: "Breaking out into song and dance.")
CardTemplate.create(color: "white", text: "Soup that is too hot.")
CardTemplate.create(color: "white", text: "Morgan Freeman's voice.")
CardTemplate.create(color: "white", text: "Getting naked and watching Nickelodeon.")
CardTemplate.create(color: "white", text: "MechaHitler.")
CardTemplate.create(color: "white", text: "Flying sex snakes.")
CardTemplate.create(color: "white", text: "The true meaning of Christmas.")
CardTemplate.create(color: "white", text: "My inner demons.")
CardTemplate.create(color: "white", text: "Pac-Man uncontrollably guzzling cum.")
CardTemplate.create(color: "white", text: "My vagina.")
CardTemplate.create(color: "white", text: "A homoerotic volleyball montage.")
CardTemplate.create(color: "white", text: "Actually taking candy from a baby.")
CardTemplate.create(color: "white", text: "Crystal meth.")
CardTemplate.create(color: "white", text: "Exactly what you'd expect.")
CardTemplate.create(color: "white", text: "Natural male enhancement.")
CardTemplate.create(color: "white", text: "Passive-aggressive Post-it notes.")
CardTemplate.create(color: "white", text: "Inappropriate yodeling.")
CardTemplate.create(color: "white", text: "Lady Gaga.")
CardTemplate.create(color: "white", text: "The Little Engine That Could.")
CardTemplate.create(color: "white", text: "Vigilante justice.")
CardTemplate.create(color: "white", text: "A death ray.")
CardTemplate.create(color: "white", text: "Poor life choices.")
CardTemplate.create(color: "white", text: "A gentle caress of the inner thigh.")
CardTemplate.create(color: "white", text: "Embryonic stem cells.")
CardTemplate.create(color: "white", text: "Nicolas Cage.")
CardTemplate.create(color: "white", text: "Firing a rifle into the air while balls deep in a squealing hog.")
CardTemplate.create(color: "white", text: "Switching to Geico&reg;.")
CardTemplate.create(color: "white", text: "The chronic.")
CardTemplate.create(color: "white", text: "Erectile dysfunction.")
CardTemplate.create(color: "white", text: "Home video of Oprah sobbing into a Lean Cuisine&reg;.")
CardTemplate.create(color: "white", text: "A bucket of fish heads.")
CardTemplate.create(color: "white", text: "50,000 volts straight to the nipples.")
CardTemplate.create(color: "white", text: "Being fat and stupid.")
CardTemplate.create(color: "white", text: "Hospice care.")
CardTemplate.create(color: "white", text: "A pyramid of severed heads.")
CardTemplate.create(color: "white", text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.")
CardTemplate.create(color: "white", text: "A subscription to Men's Fitness.")
CardTemplate.create(color: "white", text: "Crucifixion.")
CardTemplate.create(color: "white", text: "A micropig wearing a tiny raincoat and booties.")
CardTemplate.create(color: "white", text: "Some god-damn peace and quiet.")
CardTemplate.create(color: "white", text: "Used panties.")
CardTemplate.create(color: "white", text: "A tribe of warrior women.")
CardTemplate.create(color: "white", text: 'The penny whistle solo from "My Heart Will Go On."')
CardTemplate.create(color: "white", text: "An oversized lollipop.")
CardTemplate.create(color: "white", text: "Helplessly giggling at the mention of Hutus and Tutsis.")
CardTemplate.create(color: "white", text: "Not wearing pants.")
CardTemplate.create(color: "white", text: "Consensual sex.")
CardTemplate.create(color: "white", text: "Her Majesty, Queen Elizabeth II.")
CardTemplate.create(color: "white", text: "Funky fresh rhymes.")
CardTemplate.create(color: "white", text: "The art of seduction.")
CardTemplate.create(color: "white", text: "The Devil himself.")
CardTemplate.create(color: "white", text: "Advice from a wise, old black man.")
CardTemplate.create(color: "white", text: "Destroying the evidence.")
CardTemplate.create(color: "white", text: "The light of a billion suns.")
CardTemplate.create(color: "white", text: "Wet dreams.")
CardTemplate.create(color: "white", text: "Synergistic management solutions.")
CardTemplate.create(color: "white", text: "Growing a pair.")
CardTemplate.create(color: "white", text: "Silence.")
CardTemplate.create(color: "white", text: "An M16 assault rifle.")
CardTemplate.create(color: "white", text: "Poopy diapers.")
CardTemplate.create(color: "white", text: "A live studio audience.")
CardTemplate.create(color: "white", text: "The Great Depression.")
CardTemplate.create(color: "white", text: "A spastic nerd.")
CardTemplate.create(color: "white", text: "Rush Limbaugh's soft, shitty body.")
CardTemplate.create(color: "white", text: "Tickling Sean Hannity, even after he tells you to stop.")
CardTemplate.create(color: "white", text: "Stalin.")
CardTemplate.create(color: "white", text: "Brown people.")
CardTemplate.create(color: "white", text: "Rehab.")
CardTemplate.create(color: "white", text: "Capturing Newt Gingrich and forcing him to dance in a monkey suit.")
CardTemplate.create(color: "white", text: "Battlefield amputations.")
CardTemplate.create(color: "white", text: "An uppercut.")
CardTemplate.create(color: "white", text: "Shiny objects.")
CardTemplate.create(color: "white", text: "An ugly face.")
CardTemplate.create(color: "white", text: "Menstrual rage.")
CardTemplate.create(color: "white", text: "A bitch slap.")
CardTemplate.create(color: "white", text: "One trillion dollars.")
CardTemplate.create(color: "white", text: "Chunks of dead prostitute.")
CardTemplate.create(color: "white", text: "The entire Mormon Tabernacle Choir.")
CardTemplate.create(color: "white", text: "The female orgasm.")
CardTemplate.create(color: "white", text: "Extremely tight pants.")
CardTemplate.create(color: "white", text: "The Boy Scouts of America.")
CardTemplate.create(color: "white", text: "Stormtroopers.")
CardTemplate.create(color: "white", text: "Throwing a virgin into a volcano.")
